<?php

//Edit below that line!!!
// for ex. $lng[1][1]="your text"; //comment on the text
// Don't use double quotes in the texts!  

//GENERAL HEADER
$lng[1][1]="ReqHeap"; //Site title
$lng[1][2]="The Requirement Heap"; //Site description (search engines)
$lng[1][3]="requirement, requirements, heap"; //Site keywords (search engines)

//TOP
$lng[2][1]="Projekt"; //Project text
$lng[2][2]="Alle Projekte"; //All Projects text in the dropdown
$lng[2][3]="Switch"; //Switch text in button
$lng[2][4]="Willkommen"; //text
$lng[2][5]="Home"; //menu text 1 
$lng[2][6]="Sprache"; //Language text
$lng[2][7]="EN"; //Language text1
$lng[2][8]="DE"; //Language text2
$lng[2][9]="FR"; //Language text3
$lng[2][10]="IT"; //Language text4
$lng[2][11]="Login"; //Login text
$lng[2][12]="Logout"; //Logout text
$lng[2][13]="Registrieren"; //Register text
$lng[2][14]="user"; //User rights - user
$lng[2][15]="supervisor user"; //User rights - supervisor user 
$lng[2][16]="supervisor IT"; //User rights - supervisor IT
$lng[2][17]="project leader"; //User rights - project leader
$lng[2][18]="admin"; //User rights - admin
$lng[2][19]="Mein Benutzerkonto"; //menu text 3
$lng[2][20]="Projekte"; //menu text 4
$lng[2][21]="Benutzer"; //menu text 9
$lng[2][22]="Releases"; //menu text 6
$lng[2][23]="Requirement hinzufügen"; //menu text 11
$lng[2][24]="Alle zeigen"; //menu text 2
$lng[2][25]="consumer"; //User rights - consumer
$lng[2][26]="PDF Querformat"; //button for converting pdfs
$lng[2][27]="Stakeholders"; //menu text 8
$lng[2][28]="Glossar"; //menu text 9
$lng[2][29]="Statistiken"; //menu text 14
$lng[2][30]="Export Excel"; //button for converting XLS
$lng[2][31]="Export CSV"; //button for converting csv
$lng[2][32]="Baum Ansicht"; //button for viewing requirements as a tree
$lng[2][33]="Normale Ansicht"; //button for viewing requirements normally
$lng[2][34]="Subprojekte"; //menu text 5
$lng[2][35]="Testfälle"; //menu text 7
$lng[2][36]="Schlüsselwörter"; //menu text 13
$lng[2][37]="Importieren"; //menu text 12
$lng[2][38]="PDF Hochformat"; //button for converting pdfs in portrait mode

//FOOTER
$lng[3][1]="Copyright © 2007";
$lng[3][2]="About / Hilfe";

//Main page
$lng[4][1]="Mir zugewiesen";
$lng[4][2]="(Ungelöst)";
$lng[4][3]="Kürzlich modifiziert";
$lng[4][4]="(Gelöst)";
$lng[4][5]="Warten auf Bestätigung";
$lng[4][6]="Zurückgezogen";
$lng[4][7]="Projekt total";
$lng[4][8]="Sie sind nicht befugt dieses Element zu sehen!";

//Login
$lng[5][1]="Login";
$lng[5][2]="Benutzername";
$lng[5][3]="Passwort";
$lng[5][4]="Registrieren";
$lng[5][5]="Passwort vergessen";
$lng[5][6]="Login nicht korrekt!";
$lng[5][7]="*Als Gast einloggen mit guest/guest";  //text note under login area
$lng[5][8]="News";

//Register
$lng[6][1]="Register";
$lng[6][2]="Benutzername";
$lng[6][3]="Passwort";
$lng[6][4]="Passwort wiederholen ";
$lng[6][5]="Name";
$lng[6][6]="Email";
$lng[6][7]="Alle Felder müssen ausgefüllt sein!";
$lng[6][8]="Email Adresse ist nicht korrekt!";
$lng[6][9]="Passwörter sind nicht gleich!";
$lng[6][10]="Buntzername oder Passwort existiert bereits!";
$lng[6][11]="ReqHeap Registration";  //reg email text1
$lng[6][12]="Vielen Dank!";  //reg email text2
$lng[6][13]=", Ihre Registrierung war erfolgreich.";  //reg email text3
$lng[6][14]="Hier sind Ihre Benutzerdaten";  //reg email text1
$lng[6][15]="Benutzername";  //reg email text4
$lng[6][16]="Passwort";  //reg email text5
$lng[6][17]="Sie können sich hier einloggen";  //reg email text6
$lng[6][18]="Diese email Adresse existiert bereits! Bitte eine andere wählen.";
$lng[6][19]="Dieser Name existiert bereits! Bitte wählen Sie einen anderen.";
$lng[6][20]="Ein neuer Benutzer hat sich registriert";
$lng[6][21]="Ein neuer Benutzer hat sich via CSV import registriert";
$lng[6][22]="ReqHeap Passwort zurücksetzen"; 
$lng[6][23]="Ihr Passwort für ReqHeap ist zurückgesetzt worden! Neues Passwort: "; 

//Lost password
$lng[7][1]="Passwort verloren";
$lng[7][2]="Email";
$lng[7][3]="Passwort anfordern";
$lng[7][4]="Die Daten zum Benutzerkonto sind an Ihre email Adresse gesendet worden!";
$lng[7][5]="Diese email Adresse existiert nicht!";
$lng[7][6]="Passwort verloren";  //reg email text1
$lng[7][7]="Ihre Login details";  //reg email text2
$lng[7][8]="Benutzername";  //reg email text3
$lng[7][9]="Neues Passwort";  //reg email text4
$lng[7][10]="Sie können sich hier einloggen";  //reg email text5

//My profile
$lng[8][1]="Mein Benutzerkonto";
$lng[8][2]="Änderungen gespeichert!";
$lng[8][3]="Benutzername wird benötigt!";
$lng[8][4]="Name wird benötigt!";
$lng[8][5]="Email wird benötigt!";
$lng[8][6]="Benutzername existiert bereits! Bitte wählen Sie einen anderen.";
$lng[8][7]="Benutzername oder Passwort existiert bereits! Bitte wählen Sie einen/ein anderen/anderes.";
$lng[8][8]="Update";
$lng[8][9]="User level";

//projects
$lng[9][1]="Name";
$lng[9][2]="Phase";
$lng[9][3]="Status";
$lng[9][4]="Leader";
$lng[9][5]="Datum erstellt";
$lng[9][6]="Beschreibung";
$lng[9][7]="Neues Projekt erstellen";
$lng[9][8]="Entwicklung";
$lng[9][9]="Veröffentlicht";
$lng[9][10]="Erledigt";
$lng[9][11]="Privat";
$lng[9][12]="Öffentlich";
$lng[9][13]="Releases";
$lng[9][14]="ausser Dienst";
$lng[9][15]="In XML exportieren";
$lng[9][16]="Projektname"; //field Name label
$lng[9][17]="Projektphase"; //field Phase label
$lng[9][18]="Projektstatus:\nPrivat, Öffentlich oder ausser Dienst"; //field Status label - use \n for new line!
$lng[9][19]="Projektleiter"; //field Leader label
$lng[9][20]="Datum Projekt erstellt"; //field Date created label
$lng[9][21]="Projektbeschreibung"; //field Description label
$lng[9][22]="Projekt releases"; //field Releases label
$lng[9][23]="Projektautor"; //field Author label
$lng[9][24]="Project stakeholders"; //field Stakeholders label
$lng[9][25]="Stakeholders";
$lng[9][26]="Projektglossar"; //field Glossary label
$lng[9][27]="Glossar";
$lng[9][28]="Template";
$lng[9][29]="Template Projekt"; //field Template label
$lng[9][30]="Projekttestfälle"; //field cases label
$lng[9][31]="Testfälle";
$lng[9][32]="Validation";
$lng[9][33]="Evolution";

//Edit projects
$lng[10][1]="Projekt bearbeiten";
$lng[10][2]="Projekt hinzufügen";
$lng[10][3]="Projektname";
$lng[10][4]="Phase";
$lng[10][5]="Status";
$lng[10][6]="Projektleiter";
$lng[10][7]="Beschreibung";
$lng[10][8]="Datum erstellt";
$lng[10][9]="Projekt hinzufügen";
$lng[10][10]="Projekt updaten";
$lng[10][11]="Projekt löschen";
$lng[10][12]="Ein Projektname wird benötigt!";
$lng[10][13]="Sind Sie sicher? Das Projekt wird gelöscht!";
$lng[10][14]="Benutzer zuweisen";
$lng[10][15]="Speichern";
$lng[10][16]="Alle Benutzer:";
$lng[10][17]="Selektierte Benutzer:"; 
$lng[10][18]="Release zuweisen";
$lng[10][19]="Speichern";
$lng[10][20]="Alle Releases:";
$lng[10][21]="Selektierte Releases:"; 
$lng[10][22]="Releases";
$lng[10][23]="Hier können Sie Benutzer selektieren und dem Projekt zuweisen"; //field Assign users
$lng[10][24]="Hier können Sie Releases selektieren und dem Projekt zuweisen"; //field Assign release
$lng[10][25]="Dieses Projekt ist nicht mehr in Betrieb! Wenn Sie es updaten wollen, ändern Sie zuerst den Status!"; //message if a project is retired
$lng[10][26]="Stakeholder zuweisen";
$lng[10][27]="Speichern";
$lng[10][28]="Alle Stakeholders:";
$lng[10][29]="Ausgewählte Stakeholders:"; 
$lng[10][30]="Hier können Sie Stakeholder selektieren und dem Projekt zuweisen"; //field Assign stakeholders
$lng[10][31]="Glossar zuweisen";
$lng[10][32]="Speichern";
$lng[10][33]="Alle Glossarien:";
$lng[10][34]="Selektierte Glossarien:"; 
$lng[10][35]="Hier können Sie Glossarien selektieren und dem Projekt zuweisen"; //field Assign glossaries
$lng[10][36]="Template?"; 
$lng[10][37]="Hier können Sie das Projekt als Template speichern."; //field Template label
$lng[10][38]="Template laden"; 
$lng[10][39]="Hier können Sie ein bereits existierendes Projekt mit Requriements laden"; //field Load Template label
$lng[10][40]="Wählen Sie einen anderen Projektnamen!";
$lng[10][41]="Erstellen/update von einem Template";
$lng[10][42]="Subprojekte";
$lng[10][43]="Subprojekte";  //Subprojects label

//users
$lng[11][1]="Name";
$lng[11][2]="Benutzername";
$lng[11][3]="Email";
$lng[11][4]="Rechte";
$lng[11][5]="Neuen Benutzer erstellen";

//Edit users
$lng[12][1]="Benutzer bearbeiten";
$lng[12][2]="Name";
$lng[12][3]="Benutzername";
$lng[12][4]="Email";
$lng[12][5]="Rechte";
$lng[12][6]="Benutzer updaten";
$lng[12][7]="Benutzer löschen";
$lng[12][8]="Name wird benötigt!";
$lng[12][9]="Benutzername wird benötigt!";
$lng[12][10]="Email wird benötigt!";
$lng[12][11]="Email Adresse ist nicht korrekt!";
$lng[12][12]="Sind Sie sicher? Benutzer wird gelöscht!";
$lng[12][13]="Projekte zuweisen";
$lng[12][14]="Speichern";
$lng[12][15]="Alle Projekte:";
$lng[12][16]="Selektierte Projekte:"; 
$lng[12][17]="Benutzer erstellen";
$lng[12][18]="Passwort wird benötigt!";
$lng[12][19]="Passwörter stimmen nicht überein!";
$lng[12][20]="Passwort";
$lng[12][21]="Passwort wiederholen";
$lng[12][22]="Passwort zurücksetzen";
$lng[12][23]="Passwort zurücksetzen";

//releases
$lng[13][1]="Release";
$lng[13][2]="Projekt";
$lng[13][3]="Geplantes Datum";
$lng[13][4]="Datum Veröffentlichung";
$lng[13][5]="Release hinzufügen";
$lng[13][6]="Release Name"; //field Name label
$lng[13][7]="Name des zugewiesenen Projekts"; //field Project label
$lng[13][8]="Geplantes Datum"; //field Projected Date label
$lng[13][9]="Datum Veröffentlichung"; //field Released Date label
$lng[13][10]="Releasetestfälle"; //field cases label
$lng[13][11]="Testfälle";

//Edit release
$lng[14][1]="Release bearbeiten";
$lng[14][2]="Release hinzufügen";
$lng[14][3]="Name";
$lng[14][4]="Projekt";
$lng[14][5]="Geplantes Datum (tt.mm.jj)";
$lng[14][6]="Releasedatum (tt.mm.jj)";
$lng[14][7]="Release updaten";
$lng[14][8]="Release löschen";
$lng[14][9]="Release hinzufügen";
$lng[14][10]="Sind Sie sicher? Release wird gelöscht!";
$lng[14][11]="Name wird benötigt!";
$lng[14][12]="Geplantes Datum wird benötigt!";
$lng[14][13]="Geplantes Datum ist ungültig!";
$lng[14][14]="Releasedatum ist ungültig!";

//Edit requirement
$lng[15][1]="Anforderung bearbeiten";
$lng[15][2]="Neue Anforderung hinzufügen";
$lng[15][3]="Projekt";
$lng[15][4]="Titel";
$lng[15][5]="Beschreibung";
$lng[15][6]="Anforderung hinzufügen";
$lng[15][7]="Titel wird benötigt!";
$lng[15][8]="Beschreibung wird benötigt!";
$lng[15][9]="Projekt wird benötigt!";
$lng[15][10]="Status";
$lng[15][11]="Anforderungstyp";
$lng[15][12]="--";
$lng[15][13]="Priorität";
$lng[15][14]="URL";
$lng[15][15]="Gültig";
$lng[15][16]="Autor";
$lng[15][17]="Erstellungsdatum";
$lng[15][18]="Letzte Änderung";
$lng[15][19]="Datum akzeptiert";
$lng[15][20]="Benutzer akzeptiert ";
$lng[15][21]="Update Anforderung";
$lng[15][22]="Lösche Anforderung";
$lng[15][23]="Sind Sie sicher? Anforderung wird gelöscht!";
$lng[15][24]="Releases";
$lng[15][25]="*Mehrere Realeases selektieren mit gedrückter CTRL Taste";
$lng[15][26]="Ja";  //valid
$lng[15][27]="Nein";  //valid
$lng[15][28]="--Projekt auswählen--";  //project dropdown
$lng[15][29]="Veröffentlichungsdatum (tt.mm.jjjj)";  
$lng[15][30]="Zuweisen zu";  
$lng[15][31]="nicht gültig/zurückgewiesen";  
$lng[15][32]="gültig/akzeptiert";  
$lng[15][33]="ausser Dienst";  
$lng[15][34]="Interne Version";  
$lng[15][35]="Parent Anforderung";  
$lng[15][36]="Position im Anforderungsbaum";  
$lng[15][37]="-keine-";  
$lng[15][38]="Parent";  
$lng[15][39]="Baumposition";  
$lng[15][40]="Komponent";  
$lng[15][41]="Quelle";  
$lng[15][42]="Risiko level";  
$lng[15][43]="Komplexität";  
$lng[15][44]="Offene Punkte";  
$lng[15][45]="Req ID";
$lng[15][46]="(Fügen Sie 'http://' am Anfang eines externen Links hinzu)";  
$lng[15][51]="Projektname"; //label for Project field
$lng[15][52]="Releasenamen"; //label for Releases field
$lng[15][53]="Anforderunstitel"; //label for title field
$lng[15][54]="Parent Anforderung"; //label for Parent field
$lng[15][55]="Position in Anforderungsbaum"; //label for Position in requirement tree field
$lng[15][56]="Zuweisen zu"; //label for Assign to field
$lng[15][57]="Anforderungsbeschreibung"; //label for Description  field
$lng[15][58]="Anforderungsstatus"; //label for State field
$lng[15][59]="Anforderungstyp"; //label for Type field
$lng[15][60]="Anforderungspriorität"; //label for priority field
$lng[15][61]="Anforderung URL"; //label for URL field
$lng[15][62]="Anforderungskomponent"; //label for Component field
$lng[15][63]="Anforderungsquelle"; //label for Source field
$lng[15][64]="Anforderung Risiko level"; //label for Risk level field
$lng[15][65]="Anforderungskomplexität"; //label for Complexity field
$lng[15][66]="Anforderung Offene Punkte"; //label for Open points field
$lng[15][67]="Req ID"; //label for Req ID field
$lng[15][68]="Anforderung Autor"; //label for Author  field
$lng[15][69]="Anforderung Interne Version"; //label for Internal version  field
$lng[15][70]="Anforderung Erstellungsdatum"; //label for Creation date field
$lng[15][71]="Anforderung Letzte Änderung"; //label for Last change  field
$lng[15][72]="Anforderung Datum akzeptiert"; //label for Accepted Date field
$lng[15][73]="Anforerung Benutzer akzeptiert"; //label for Accepted User field
$lng[15][74]="Das Projekt dieser Anforderung ist ausser Betrieb. Die Anforderung kann nicht bearbeitet werden!"; 
$lng[15][75]="Anforderung klonen"; 
$lng[15][76]="Stakeholder"; 
$lng[15][77]="Name der Stakeholder"; //label for Stakeholders  field
$lng[15][78]="Ist abhängig von";
$lng[15][79]="Abhängigkeiten zwischen Anforderungen"; //label for Depends on  field
$lng[15][80]="Konflikte";
$lng[15][81]="Konflikte zwischen Anforderungen"; //label for Conflicts field
$lng[15][82]="Zufriedenheit";
$lng[15][83]="Zufriedenheit"; //label for Satisfaction field
$lng[15][84]="Unzufriedenheit";
$lng[15][85]="Unzufriedenheit"; //label for Dissatisfaction field
$lng[15][86]="Glossar"; 
$lng[15][87]="Glossarnamen"; //label for Glossary  field
$lng[15][88]="Gewicht"; 
$lng[15][89]="Anforderungsgewicht"; //label for Weight  field
$lng[15][90]="Stub/Überschrift"; 
$lng[15][91]="Sie können Stub- oder Überschrifts-Anforderungen erstellen und die Informationen später hinzufügen"; //label for Stub/Heading  field
$lng[15][92]="Normale Anforderung"; 
$lng[15][93]="Stub Anforderung"; 
$lng[15][94]="Stub hinzufügen"; 
$lng[15][95]="Normale Anforderung hinzufügen"; 
$lng[15][96]="Sie können Stub- oder Überschrifts-Anforderungen erstellen und die Informationen später hinzufügen"; //label for Stub  button
$lng[15][97]="Subprojekt"; 
$lng[15][98]="Subprojekt"; //label for Subproject 
$lng[15][99]="Subprojekte"; 
$lng[15][100]="Subprojekte"; //label for Subprojects
$lng[15][101]="(tiefste)"; //label for priority dropdown
$lng[15][102]="(höchste)"; //label for priority dropdown
$lng[15][103]="Testfälle";
$lng[15][104]="Testfälle"; //label for Test cases field
$lng[15][105]="Überschrift hinzufügen"; 
$lng[15][106]="Überschrift-Anforderung"; 
$lng[15][107]="Schlüsselwörter";
$lng[15][108]="Schlüsselwörter"; //label for Keywords field
$lng[15][109]="Bitte geben Sie eine Zahl in das ‘Gewicht’-Feld ein";
$lng[15][110]="Schlüsselwörter hinzufügen"; 
$lng[15][111]="Schlüsselwörter hinzufügen"; //label for Add keywords
$lng[15][112]="(Komma getrennt - z.B. keyword1,keyword2,keyword3, etc.)"; 
$lng[15][113]="Benutzerdefinierte Felder"; 
$lng[15][114]="Kommentare"; 

//view requirement
$lng[16][1]="Zeige Anforderung";
$lng[16][2]="Bearbeiten";
$lng[16][3]="Veröffentlichungsdatum";  
$lng[16][4]="Erweiterte Ansicht ";  
$lng[16][5]="Reduzierte Ansicht";  
$lng[16][6]="Verlauf";  
$lng[16][7]="Kommentare";  
$lng[16][8]="Kommentar absenden";  
$lng[16][9]="Autor";  
$lng[16][10]="Datum";  
$lng[16][11]="Löschen";  
$lng[16][12]="Sind Sie sicher? Kommenatr wird gelöscht!";  
$lng[16][13]="Verstecke/Zeige Kommentare";  
$lng[16][14]="Verstecke/Zeige Verlauf";  
$lng[16][15]="PDF";  
$lng[16][16]="Verstecke/Zeige Anforderungsbaum";  
$lng[16][17]="Anforderungsbaum";  
$lng[16][18]="Zu dieser Version zurückkehren";  
$lng[16][19]="Speichern";  
$lng[16][20]="Es ist ein Problem mit dem Anforderungsbaum aufgetreten – Vermutlich existieren verschachtelte Anforderungen! Bitte prüfen!";  
$lng[16][21]="PDF Hochformat";  

//view all
$lng[17][1]="ID";
$lng[17][2]="Titel";
$lng[17][3]="Autor";
$lng[17][4]="Zugewiesen zu";
$lng[17][5]="Priorität";
$lng[17][6]="Erstellungsdatum";
$lng[17][7]="Projekt";
$lng[17][8]="Datum der letzten Änderung";
$lng[17][9]="Gültig";
$lng[17][10]="Warten auf die Akzeptierung";
$lng[17][11]="Ausser Dienst";
$lng[17][12]="Zugewiesen";
$lng[17][13]="Rückmeldung";
$lng[17][14]="Festgelegt";
$lng[17][15]="Behoben";
$lng[17][16]="Zustand";
$lng[17][17]="Suche";
$lng[17][18]="Text";
$lng[17][19]="Projektleiter";
$lng[17][20]="Datum";
$lng[17][21]="Beschreibung";
$lng[17][22]="Name";
$lng[17][23]="Phase";
$lng[17][24]="Status";
$lng[17][25]="Absenden";
$lng[17][26]="-nicht ändern";
$lng[17][27]="-slektion zurücksetzen";
$lng[17][28]="Ausgewählten Anforderungen zuweisen:";
$lng[17][29]="--zurücksetzen";
$lng[17][30]="Zustand";  
$lng[17][31]="-Zustand nicht ändern";  
$lng[17][32]="gültig/akzeptiert";  
$lng[17][33]="nicht gültig/zurückgewiesen";  
$lng[17][34]="ausser Dienst";  
$lng[17][35]="Projekt";  
$lng[17][36]="Release";  
$lng[17][37]="Benutzer";  
$lng[17][38]="-Projekt nicht ändern";
$lng[17][39]="Priorität";  
$lng[17][40]="-Priorität nicht ändern";  
$lng[17][41]="Quelle";  
$lng[17][42]="Komponent";
$lng[17][43]="Es existieren Anforderungen die einem Projekt zugewiesen sind, das nicht mehr in Betrieb ist. Diese werden nicht geupdated!";
$lng[17][44]="Baum";
$lng[17][45]="Stub/Überschrift";
$lng[17][46]="--alle anzeigen--";
$lng[17][47]="--nur Stub anzeigen--";
$lng[17][48]="Offene Fragen";
$lng[17][49]="--alle anzeigen--";
$lng[17][50]="--nur offene Fragen anzeigen--";
$lng[17][51]="--nur Überschriften anzeigen--";
$lng[17][52]="Schlüsselwörter";  //keywords search dropdown
$lng[17][53]="Oder";  //keywords search radio button choice 1
$lng[17][54]="Und";  //keywords search radio button choice 2
$lng[17][55]="Leere Felder";  //empty fields search dropdown
$lng[17][56]="Autor";  //empty fields choice 1
$lng[17][57]="Zugewiesen zu";  //empty fields choice 2
$lng[17][58]="Komponente";  //empty fields choice 3
$lng[17][59]="Release";  //empty fields choice 4
$lng[17][60]="Schlüsselwörter";  //empty fields choice 5
$lng[17][61]="Testfälle";  //empty fields choice 6
$lng[17][62]="* Die Position der Anforderungen im Baum, können Sie via Drag and Drop verändern";  //text 1
$lng[17][63]="** Bitte seien Sie vorsichtig und erstellen Sie keine endlos verschachtelten Anforderungen, sonst verschwinden diese vom der Baumansicht! Wenn erstell, können Sie diese beheben, indem Sie sie bearbeiten und die Parents entfernen!";  //warning text 2
$lng[17][64]="Undo";  //Undo button label
$lng[17][65]="Redo";  //Redo button label
$lng[17][66]="Kann nicht rückgängig gemacht werden!"; 
$lng[17][67]="Kann nicht wiederhergestellt werden!"; 
$lng[17][68]="Pos"; //label at top of the tree table
$lng[17][69]="* Drag and drop um die Parent Position zu verändern"; //text 1
$lng[17][70]="Position wechseln"; //text 1
$lng[17][71]="Parent"; 
$lng[17][72]="Autor des Kommentars";
$lng[17][73]="Anf ID";
$lng[17][74]="Von";
$lng[17][75]="bis";
$lng[17][76]="Pos";
$lng[17][77]="Alle anwählen";
$lng[17][78]="Alle abwählen";
$lng[17][79]="Filter zurücksetzten";
$lng[17][80]="Subprojekt";  
$lng[17][81]="-Subprojekt nicht ändern";
$lng[17][82]="Keine Anforderungen gefunden!";
$lng[17][83]="oder";

//add comment
$lng[18][1]="Kommentar absenden";
$lng[18][2]="Absenden";
$lng[18][3]="Frage?";
$lng[18][4]="Wenn Sie eine Antwort für den Kommentar benötigen";  //Label for Question

//RSS feed
$lng[19][1]=" feed"; //anybody's feed
$lng[19][2]="Feed beinhaltet die letzten Änderungen in den Anforderungen meines Projekts";
$lng[19][3]="Anforderungsänderungen";

//XML for projects
$lng[20][1]="project";
$lng[20][2]="name";
$lng[20][3]="description";
$lng[20][4]="phase";
$lng[20][5]="status";
$lng[20][6]="leader";
$lng[20][7]="creation_date"; //no blank spaces allowed!
$lng[20][8]="release";
$lng[20][9]="name"; //release name
$lng[20][10]="assigned_users"; //no blank spaces allowed!
$lng[20][11]="name"; //assigned users name

//install/diagnostics.php
$lng[21][1]=" Testing DB connection...";
$lng[21][2]=" - DB connection can't be established! Please check for valid DB name or username or password.";
$lng[21][3]=" 1.DB connected successfully!";
$lng[21][4]=" Testing DB integrity...";
$lng[21][5]=" 2.All DB tables are present!";
$lng[21][6]=" - Table 'admin_access' is missing!";
$lng[21][7]=" - Table 'comments' is missing!";
$lng[21][8]=" - Table 'project_releases' is missing!";
$lng[21][9]=" - Table 'project_users' is missing!";
$lng[21][10]=" - Table 'projects' is missing!";
$lng[21][11]=" - Table 'releases' is missing!";
$lng[21][12]=" - Table 'requirements' is missing!";
$lng[21][13]=" - Table 'requirements_history' is missing!";
$lng[21][14]=" - Table 'users' is missing!";
$lng[21][15]=" Testing folders permissions...";
$lng[21][16]=" 3.All folders are present and with sufficient rights!";
$lng[21][17]=" - Folder 'admin' is missing or with unsufficient rights! Should be 0755.";
$lng[21][18]=" - Folder 'ini/lng' is missing or with unsufficient rights! Should be 0755.";
$lng[21][19]=" - Language file in 'ini/lng' is missing!";
$lng[21][20]=" - Folder 'admin/css' is missing or with unsufficient rights! Should be 0755.";
$lng[21][21]=" - Folder 'admin/img' is missing or with unsufficient rights! Should be 0755.";
$lng[21][22]=" - Folder 'admin/inc' is missing or with unsufficient rights! Should be 0755.";
$lng[21][23]=" - Folder 'FCKeditor' is missing or with unsufficient rights! Should be 0755.";
$lng[21][24]=" - Folder 'img' is missing or with unsufficient rights! Should be 0755.";
$lng[21][25]=" - Folder 'install' is missing or with unsufficient rights! Should be 0755.";
$lng[21][26]=" - Folder 'RSS' is missing or with unsufficient rights! Should be 0777.";
$lng[21][27]=" - Folder 'ini' is missing or with unsufficient rights! Should be 0777.";
$lng[21][28]=" - Folder 'ini/bkps' is missing or with unsufficient rights! Should be 0777.";
$lng[21][29]=" - Folder 'ini/lng' is missing or with unsufficient rights! Should be 0777.";
$lng[21][30]=" - Folder 'ini/txts' is missing or with unsufficient rights! Should be 0777.";
$lng[21][31]=" Getting project statistics...";
$lng[21][32]=" 1.Total number of projects: ";
$lng[21][33]=" - public projects : ";
$lng[21][34]=" - private projects: ";
$lng[21][35]=" - retired projects: ";
$lng[21][36]=" 2.Total number of requirements: ";
$lng[21][37]=" 3.Total number of users: ";
$lng[21][38]=" - consumer : ";
$lng[21][39]=" - user : ";
$lng[21][40]=" - supervisor user : ";
$lng[21][41]=" - supervisor IT : ";
$lng[21][42]=" - project leader : ";
$lng[21][43]=" Testing rich HTML editor availability...";
$lng[21][44]=" 4.If you can see a sample of the rich HTML editor below, the editor has been loaded successfully, otherwise please check if it is installed correctly!";
$lng[21][45]=" - Settings file - params.php in 'ini/' is missing!";
$lng[21][46]=" 5.Check if the PDF script is installed and running correctly (PHP5 only!) - ";
$lng[21][47]=" click here ";
$lng[21][48]=" - If you can view a PDF file then the script is installed, otherwise please check the installation and settings of dompdf-0.5.1";
$lng[21][49]=" - Table 'project_stakeholders' is missing!";
$lng[21][50]=" - Table 'stakeholders' is missing!";
$lng[21][51]=" - Table 'project_glossary' is missing!";
$lng[21][52]=" - Table 'glossary' is missing!";
$lng[21][53]=" 5.Check if the Excel script is installed and running correctly (PHP5 only!) - ";
$lng[21][54]=" click here ";
$lng[21][55]=" - If you can view an Excel file then the script is installed, otherwise please check the installation and settings of php_writeexcel-0.3.0";
$lng[21][56]=" - Table 'user_fields' is missing!";
$lng[21][57]=" - Table 'subprojects' is missing!";
$lng[21][58]=" - Table 'cases' is missing!";
$lng[21][59]=" - Table 'project_cases' is missing!";
$lng[21][60]=" - Table 'release_cases' is missing!";
$lng[21][61]=" - Table 'keywords' is missing!";
$lng[21][62]=" - Table 'tree history' is missing!";
$lng[21][63]=" - Table 'export_fields' is missing!";
$lng[21][64]="Your SQL version is ";
$lng[21][65]="Your PHP version is ";

//stakeholders
$lng[22][1]="Stakeholder";
$lng[22][2]="Projekt";
$lng[22][3]="Funktion";
$lng[22][4]="Email";
$lng[22][5]="Neuer Stakeholder hinzufügen";
$lng[22][6]="Stakeholder Name"; //field Name label
$lng[22][7]="Name des zugewiesenen Projekts"; //field Project label
$lng[22][8]="Funktion"; //field Function label
$lng[22][9]="Email"; //field Email label

//Edit stakeholder
$lng[23][1]="Stakeholder bearbeiten";
$lng[23][2]="Stakeholder hinzufügen";
$lng[23][3]="Name";
$lng[23][4]="Projekt";
$lng[23][5]="Funktion";
$lng[23][6]="Email";
$lng[23][7]="Update Stakeholder";
$lng[23][8]="Stakeholder Löschen";
$lng[23][9]="Stakeholder hinzufügen";
$lng[23][10]="Sind Sie sicher? Stakeholder wird gelöscht!";
$lng[23][11]="Name wird benötigt!";
$lng[23][12]="Interessen";
$lng[23][13]="Name"; //name label
$lng[23][14]="Funktion"; //Function label
$lng[23][15]="Email"; //Email label
$lng[23][16]="Interessen"; //Interests label
$lng[23][17]="Stakeholder verwalten";

//glossary
$lng[24][1]="Glossar";
$lng[24][2]="Projekt";
$lng[24][3]="Begriff";
$lng[24][4]="Abkürzung";
$lng[24][5]="Neues Glossar hinzufügen";
$lng[24][6]="Glossar ID"; //field Glossary/ID label
$lng[24][7]="Name des zugewiesenen Projekts"; //field Project label
$lng[24][8]="Begriff"; //field Term label
$lng[24][9]="Abkürzung"; //field Abbreviation label

//Edit glossary
$lng[25][1]="Glossar bearbeiten";
$lng[25][2]="Glossar hinzufügen";
$lng[25][3]="ID";
$lng[25][4]="Projekt";
$lng[25][5]="Begriff";
$lng[25][6]="Abkürzung";
$lng[25][7]="Update Glossar";
$lng[25][8]="Glossar löschen";
$lng[25][9]="Glossar hinzufügen";
$lng[25][10]="Sind Sie sicher? Glossar wird gelöscht!";
$lng[25][11]="ID wird benötigt!";
$lng[25][12]="Beschreibung";
$lng[25][13]="ID"; //ID label
$lng[25][14]="Begriff"; //Term label
$lng[25][15]="Abkürzung"; //Abreviation label
$lng[25][16]="Beschreibung"; //Description label
$lng[25][17]="Glossar verwalten";

//Statistics
$lng[26][1]="Projekt Statistiken";
$lng[26][2]="Projektname: ";
$lng[26][3]="Projekt Releases: ";
$lng[26][4]="Anzahl Anforderungen: ";
$lng[26][5]="Anforderugnen zugewiesen zu: ";
$lng[26][6]="Anforderungsautoren: ";

//Edit subprojects
$lng[27][1]="Subprojekt bearbeiten";
$lng[27][2]="Subprojekt hinzufügen";
$lng[27][3]="Subprojectname";
$lng[27][4]="Beschreibung";
$lng[27][5]="Parent Projekt";
$lng[27][6]="Update Subprojekt";
$lng[27][7]="Subprojekt löschen";
$lng[27][8]="Ein Subprojektname wird benötigt!";
$lng[27][9]="Sind Sie sicher? Subprojekt wird gelöscht!";
$lng[27][10]="Subprojektname";  //Subproject name label
$lng[27][11]="Subprojektbeschreibung"; //Subproject description label
$lng[27][12]="Parent Projekt";//Parent project label

//subprojects
$lng[28][1]="Name";
$lng[28][2]="Beschreibung";
$lng[28][3]="Parent Projekt";
$lng[28][4]="Erstelle neues Subprojekt";
$lng[28][5]="Subprojektname"; //field Subproject label
$lng[28][6]="Subprojektbeschreibung"; //field Subproject label
$lng[28][7]="Parent Projekt"; //field Parent project label
$lng[28][8]="Subprojekt"; //field Parent project label

//test cases
$lng[29][1]="ID";
$lng[29][2]="Name";
$lng[29][3]="Beschreibung";
$lng[29][4]="Gewünschtes Resultat";
$lng[29][5]="Status";
$lng[29][6]="Testfallname"; //field Name label
$lng[29][7]="Beschreibung"; //field Description label
$lng[29][8]="Gewünschtes Resultat"; //field Desired result label
$lng[29][9]="Status - aktiv oder nicht"; //field Status  label
$lng[29][10]="Neuer Testfall hinzufügen";
$lng[29][11]="Bearbeiten"; //Edit case button
$lng[29][12]="Ansicht";  //View case button
$lng[29][13]="Reduzierte Ansicht";  //View case button
$lng[29][14]="Erweiterte Ansicht";  //View case button

//Edit cases
$lng[30][1]="Testfall bearbeiten";
$lng[30][2]="Testfall hinzufügen";
$lng[30][3]="Name";
$lng[30][4]="Beschreibung";
$lng[30][5]="Gewünschtes Resultat";
$lng[30][6]="Status";
$lng[30][7]="Update Testfall";
$lng[30][8]="Testfall löschen";
$lng[30][9]="Name wird benötigt!";
$lng[30][10]="Sind Sie sicher? Testfall wird gelöscht!";
$lng[30][11]="Speichern";
$lng[30][12]="Name";  //Name label
$lng[30][13]="Beschreibung";  //Description label
$lng[30][14]="Gewünschtes Resultat";  //Desired result label
$lng[30][15]="Status";  //Status label
$lng[30][16]="aktiv"; //Status options
$lng[30][17]="inaktiv";  //Status options
$lng[30][18]="Löschen";
$lng[30][19]="Projekte zuweisen";
$lng[30][20]="Hier können Sie Projekte auswählen und dem Testfall zuweisen"; //Assign projects
$lng[30][21]="Alle Projekte:";
$lng[30][22]="Ausgewählte Projekte:"; 
$lng[30][23]="Release zuweisen";
$lng[30][24]="Hier können Sie Release auswählen und dem Testfall zuweisen"; //Assign releases
$lng[30][25]="Alle Release:";
$lng[30][26]="Ausgewählte Release:"; 

//cases
$lng[31][1]="Testfall";
$lng[31][2]="Name";
$lng[31][3]="Beschreibung";
$lng[31][4]="Gewünschtes Resultat";
$lng[31][5]="Status";
$lng[31][6]="inaktiv"; 
$lng[31][7]="aktiv"; 
$lng[31][8]="Exportieren als PDF";
$lng[31][9]="Name"; //field name
$lng[31][10]="Beschreibung"; //field Description
$lng[31][11]="Gewünschtes Resultat"; //field Desired result label
$lng[31][12]="Status:\naktiv, inaktiv"; //field Status label - use \n for new line!
$lng[31][13]="Gewünschtes Resultat"; //field Desired result
$lng[31][14]="Projekte"; 
$lng[31][15]="Release"; 
$lng[31][16]="Anforderungen"; 
$lng[31][17]="Projekt Testfälle"; //field Case projects label
$lng[31][18]="Release Testfälle"; //field Case releases label
$lng[31][19]="Anforderung Testfälle"; //field Case requirements label
$lng[31][20]="Exportieren als PDF"; //Export into PDF button

//manage keywords
$lng[32][1]="Nein";
$lng[32][2]="Schlüsselwort";
$lng[32][3]="Schlüsselwort"; //field Keyword label
$lng[32][4]="Neues Schlüsselwort hinzufügen";

//Edit keyword
$lng[33][1]="Schlüsselwort bearbeiten";
$lng[33][2]="Schlüsselwort hinzufügen";
$lng[33][3]="Name";
$lng[33][4]="Update Schlüsselwort";
$lng[33][5]="Schlüsselwort löschen";
$lng[33][6]="Sind Sie sicher? Keyword wird gelöscht!";
$lng[33][7]="Name wird benötigt!";
$lng[33][8]="Name"; //name label
$lng[33][9]="Schlüsselwörter verwalten";

//Import
$lng[34][1]="CSV Datei importieren";
$lng[34][2]="Bitte Datei auswählen: ";
$lng[34][3]="File Hochladen";
$lng[34][4]="Nur CSV Dateien warden akzeptiert!";
$lng[34][5]="Die Datei ist leer oder ist nicht korrekt formatiert!";
$lng[34][6]="Bitte ein Projekt erstellen '";  //error text 1 part 1
$lng[34][7]="' zuerst!";  //error text 1 part 2
$lng[34][8]="Es existiert bereits eine Anforderung '";  //error text 2
$lng[34][9]="Kein Projekt oder falscher Projektname in Zeile ";  //error text 3
$lng[34][10]="Kein Anforderungstitel in Zeile ";  //error text 4
$lng[34][11]="Akzeptiertes CSV Format: Projekt;Autor;Quelle;Datum(tt.mm.jjjj);Titel;Beschreibung;Schlüsselwort 1;Schlüsselwort 2;Schlüsselwort 3;Offene Punkte";
$lng[34][12]="Datensätze eingefügt!";
$lng[34][13]="Bitte lassen Sie oben eine Zeile als Kopfzeile frei";
$lng[34][14]="Projekt zuerst leeren?";
$lng[34][15]="Die Datei ist nicht im UTF-8 Format!";
$lng[34][16]="Sie können die folgende CSV Datei als Vorlage benutzen";
$lng[34][17]="Datei herunterladen";

//pdf fields
$lng[35][1]="Felder der Anforderungen die exportiert werden sollen";
$lng[35][2]="PDF erstellen";
$lng[35][3]="Datei hinaufladen";
$lng[35][4]="Vorlage";
$lng[35][5]="--Vorlage laden--";
$lng[35][6]="Vorlage speichern";
$lng[35][7]="Vorlage löschen";
$lng[35][8]="XLS erstellen";

// ADMIN / CPANEL 
$lng[99][1]="Willkommen zum ReqHeap Bedienfeld "; 
$lng[99][2]="Benutzername:"; 
$lng[99][3]="Passwort:"; 
$lng[99][4]="Sprache:"; 
$lng[99][5]="Login"; 
$lng[99][6]="Menu"; 
$lng[99][7]="Sprachdateien"; 
$lng[99][8]="Dropdown texte"; 
$lng[99][9]="Admin Konto"; 
$lng[99][10]="Logout"; 
$lng[99][11]="Benutzername wird benötigt!"; 
$lng[99][12]="Passwort wird benötigt!"; 
$lng[99][13]="ADMIN KONTO"; 
$lng[99][14]="Update"; 
$lng[99][15]="DROPDOWN TEXTE"; 
$lng[99][16]="--wählen Sie eine Datei--"; 
$lng[99][17]="HTML ist hier möglich!"; 
$lng[99][18]="Speichern"; 
$lng[99][19]="SPRACHDATEIEN"; 
$lng[99][20]="DROPDOWN TEXT"; 
$lng[99][21]="Neu";
$lng[99][22]="Auf fehlende Elemente prüfen"; //lang files
$lng[99][23]="Ganze Zeile fehlt: ";
$lng[99][24]="Element fehlt: ";
$lng[99][25]="Aktion";
$lng[99][26]="Sind Sie sicher? Der Datensatz wird gelöscht!";
$lng[99][27]="Template laden";
$lng[99][28]="Aktionen";
$lng[99][29]="Sind Sie sicher? Datensatz wird gelöscht!";
$lng[99][30]="Neuer hinzufügen";
$lng[99][31]="Zurück";
$lng[99][32]="Einfügen";
$lng[99][33]="";
$lng[99][34]="Konfigurationsdatei";
$lng[99][35]="Resultate überprüfen";
$lng[99][36]=" version";
$lng[99][37]="Benutzerdefinierte Felder";
$lng[99][38]="Benutzerdefiniertes Feld";
$lng[99][39]="Name in Englisch";
$lng[99][40]="Name in Deutsch";
$lng[99][41]="Name in Französisch";
$lng[99][42]="Name in Italienisch";
$lng[99][43]="Hilfetext in Englisch";
$lng[99][44]="Hilfetext in Deutsch";
$lng[99][45]="Hilfetext in Französisch";
$lng[99][46]="Hilfetext in Italienisch";
$lng[99][47]="Typ";
$lng[99][48]="text";
$lng[99][49]="dropdown";
$lng[99][50]="Werte";
$lng[99][51]="Nur ausfüllen, wenn ein Dropdown Typ ausgewählt wurde.<br>Werte müssen Komma getrennt sein!";
$lng[99][52]="Zum Beispiel: tief, mittel, hoch or 1,2,3,4,5";
$lng[99][53]="*wird benötigt";
$lng[99][54]="*Um ein Feld zu entfernen, einfach 'Name in Deutsch' leer lassen";
$lng[99][55]="Existierende Templates: ";  
$lng[99][56]="IT-Projekt 1";  //name of first template
$lng[99][57]="Template laden";  //Load template button
$lng[99][58]="Dieses Template wurde bereits geladen!";  
$lng[99][59]="Template wurde erfolgreich geladen!";  
?>  
       


 	  	 
