<?php

//Edit below that line!!!
// for ex. $lng[1][1]="your text"; //comment on the text
// Don't use double quotes in the texts!  

//GENERAL HEADER
$lng[1][1]="ReqHeap"; //Site title
$lng[1][2]="The Requirement Heap"; //Site description (search engines)
$lng[1][3]="requirement, requirements, heap"; //Site keywords (search engines)

//TOP
$lng[2][1]="Project"; //Project text
$lng[2][2]="All Projects"; //All Projects text in the dropdown
$lng[2][3]="Switch"; //Switch text in button
$lng[2][4]="Welcome"; //text
$lng[2][5]="Home"; //menu text 1 
$lng[2][6]="Language"; //Language text
$lng[2][7]="EN"; //Language text1
$lng[2][8]="DE"; //Language text2
$lng[2][9]="FR"; //Language text3
$lng[2][10]="IT"; //Language text4
$lng[2][11]="Login"; //Login text
$lng[2][12]="Logout"; //Logout text
$lng[2][13]="Register"; //Register text
$lng[2][14]="user"; //User rights - user
$lng[2][15]="supervisor user"; //User rights - supervisor user 
$lng[2][16]="supervisor IT"; //User rights - supervisor IT
$lng[2][17]="project leader"; //User rights - project leader
$lng[2][18]="admin"; //User rights - admin
$lng[2][19]="My Account"; //menu text 3
$lng[2][20]="Projects"; //menu text 4
$lng[2][21]="Users"; //menu text 9
$lng[2][22]="Releases"; //menu text 6
$lng[2][23]="Add Requirement"; //menu text 11
$lng[2][24]="View All"; //menu text 2
$lng[2][25]="consumer"; //User rights - consumer
$lng[2][26]="PDF landscape"; //button for converting pdfs in landscape mode
$lng[2][27]="Stakeholders"; //menu text 8
$lng[2][28]="Glossary"; //menu text 9
$lng[2][29]="Statistics"; //menu text 14
$lng[2][30]="Export Excel"; //button for converting XLS
$lng[2][31]="Export Excel TSV/CSV"; //button for converting csv
$lng[2][32]="Tree view"; //button for viewing requirements as a tree
$lng[2][33]="Normal view"; //button for viewing requirements normally
$lng[2][34]="Subprojects"; //menu text 5
$lng[2][35]="Test cases"; //menu text 7
$lng[2][36]="Keywords"; //menu text 13
$lng[2][37]="Import"; //menu text 12
$lng[2][38]="PDF portrait"; //button for converting pdfs in portrait mode
$lng[2][39]="Components"; //menu text 8
$lng[2][40]="Reviews"; //menu text 8
$lng[2][41]="Export CSV (allows import)"; //button for converting csv

//FOOTER
$lng[3][1]="Copyright © 2007";
$lng[3][2]="About / Help";

//Main page
$lng[4][1]="Assigned to Me";
$lng[4][2]="(Unresolved)";
$lng[4][3]="Recently Modified";
$lng[4][4]="(Resolved)";
$lng[4][5]="Waiting for Acceptance";
$lng[4][6]="Retired";
$lng[4][7]="Project total";
$lng[4][8]="You don't have permissions to see this article!";
$lng[4][9]="Display";

//Login
$lng[5][1]="Login";
$lng[5][2]="Username";
$lng[5][3]="Password";
$lng[5][4]="Register";
$lng[5][5]="Lost password";
$lng[5][6]="Login incorrect!";
$lng[5][7]="*As guest login with guest/guest";  //text note under login area
$lng[5][8]="News";

//Register
$lng[6][1]="Register";
$lng[6][2]="Username";
$lng[6][3]="Password";
$lng[6][4]="Re-enter password";
$lng[6][5]="Name";
$lng[6][6]="Email";
$lng[6][7]="All fields are required!";
$lng[6][8]="Email address is not correct!";
$lng[6][9]="Passwords don't match!";
$lng[6][10]="Such username or password already exists! Please, choose another.";
$lng[6][11]="ReqHeap Registration";  //reg email text1
$lng[6][12]="Thank you";  //reg email text2
$lng[6][13]=", your registration was successfull.";  //reg email text3
$lng[6][14]="Here are your login details";  //reg email text1
$lng[6][15]="Username";  //reg email text4
$lng[6][16]="Password";  //reg email text5
$lng[6][17]="You can login here";  //reg email text6
$lng[6][18]="Such email already exists! Please, choose another.";
$lng[6][19]="Such name already exists! Please, choose another.";
$lng[6][20]="New user registration";
$lng[6][21]="New user registration through CSV import";
$lng[6][22]="ReqHeap password reset"; 
$lng[6][23]="Your password for ReqHeap has been reset! New password: "; 

//Lost password
$lng[7][1]="Lost password";
$lng[7][2]="Email";
$lng[7][3]="Request password";
$lng[7][4]="Your account info has been sent to your email address!";
$lng[7][5]="Such email doesn't exist!";
$lng[7][6]="Lost password";  //reg email text1
$lng[7][7]="Your login details";  //reg email text2
$lng[7][8]="Username";  //reg email text3
$lng[7][9]="New password";  //reg email text4
$lng[7][10]="You can login here";  //reg email text5

//My profile
$lng[8][1]="My account";
$lng[8][2]="Changes saved!";
$lng[8][3]="Username is required!";
$lng[8][4]="Name is required!";
$lng[8][5]="Email is required!";
$lng[8][6]="Such username already exists! Please, choose another.";
$lng[8][7]="Such username or password already exists! Please, choose another.";
$lng[8][8]="Update";
$lng[8][9]="User level";

//projects
$lng[9][1]="Name";
$lng[9][2]="Phase";
$lng[9][3]="Status";
$lng[9][4]="Leader";
$lng[9][5]="Date created";
$lng[9][6]="Description";
$lng[9][7]="Create new project";
$lng[9][8]="development";
$lng[9][9]="released";
$lng[9][10]="finished";
$lng[9][11]="private";
$lng[9][12]="public";
$lng[9][13]="Releases";
$lng[9][14]="retired";
$lng[9][15]="Export in xml";
$lng[9][16]="Project name"; //field Name label
$lng[9][17]="Project phase"; //field Phase label
$lng[9][18]="Project status:\nprivate, public or retired"; //field Status label - use \n for new line!
$lng[9][19]="Project leader"; //field Leader label
$lng[9][20]="Project date created"; //field Date created label
$lng[9][21]="Project description"; //field Description label
$lng[9][22]="Project releases"; //field Releases label
$lng[9][23]="Project author"; //field Author label
$lng[9][24]="Project stakeholders"; //field Stakeholders label
$lng[9][25]="Stakeholders";
$lng[9][26]="Project glossary"; //field Glossary label
$lng[9][27]="Glossary";
$lng[9][28]="Template";
$lng[9][29]="Template project"; //field Template label
$lng[9][30]="Project cases"; //field cases label
$lng[9][31]="Cases";
$lng[9][32]="validation";
$lng[9][33]="evolution";
$lng[9][34]="show retired projects";
$lng[9][35]="Components";
$lng[9][36]="Components"; //field Components label
$lng[9][37]="Reviews";
$lng[9][38]="Reviews"; //field Reviews label

//Edit projects
$lng[10][1]="Edit project";
$lng[10][2]="Add project";
$lng[10][3]="Project name";
$lng[10][4]="Phase";
$lng[10][5]="Status";
$lng[10][6]="Project leader";
$lng[10][7]="Description";
$lng[10][8]="Date created";
$lng[10][9]="Add project";
$lng[10][10]="Update project";
$lng[10][11]="Delete project";
$lng[10][12]="A project name is required!";
$lng[10][13]="Are you sure? Project will be deleted!";
$lng[10][14]="Assign users";
$lng[10][15]="Save";
$lng[10][16]="All Users:";
$lng[10][17]="Selected Users:"; 
$lng[10][18]="Assign release";
$lng[10][19]="Save";
$lng[10][20]="All Releases:";
$lng[10][21]="Selected Releases:"; 
$lng[10][22]="Releases";
$lng[10][23]="Here you can select and assign users to the project"; //field Assign users
$lng[10][24]="Here you can select and assign releases to the project"; //field Assign release
$lng[10][25]="This project is retired! If you need to update it, please change it's status first!"; //message if a project is retired
$lng[10][26]="Assign stakeholders";
$lng[10][27]="Save";
$lng[10][28]="All stakeholders:";
$lng[10][29]="Selected Stakeholders:"; 
$lng[10][30]="Here you can select and assign stakeholders to the project"; //field Assign stakeholders
$lng[10][31]="Assign glossary";
$lng[10][32]="Save";
$lng[10][33]="All glossaries:";
$lng[10][34]="Selected Glossaries:"; 
$lng[10][35]="Here you can select and assign glossaries to the project"; //field Assign glossaries
$lng[10][36]="Template?"; 
$lng[10][37]="Here you can save the project as a template for others to load and use it"; //field Template label
$lng[10][38]="Load template"; 
$lng[10][39]="Here you can load a already created project with requirements"; //field Load Template label
$lng[10][40]="Choose a different project name!";
$lng[10][41]="Create/update from template";
$lng[10][42]="Subprojects";
$lng[10][43]="Subprojects";  //Subprojects label
$lng[10][44]="Here you can select and assign components to the project"; //field Assign components
$lng[10][45]="Assign components";
$lng[10][46]="All components:";
$lng[10][47]="Selected components:"; 
$lng[10][48]="Here you can select and assign keywords to the project"; //field Assign keywords
$lng[10][49]="Assign keywords";
$lng[10][50]="All keywords:";
$lng[10][51]="Selected keywords:"; 
$lng[10][52]="Delete requirements?"; 
$lng[10][53]="Delete requirements?"; //label
$lng[10][54]="yes"; 
$lng[10][55]="no";
$lng[10][56]="Assign requirements";
$lng[10][57]="Here you can select and assign requirements to the review"; //field Assign requirements

//users
$lng[11][1]="Name";
$lng[11][2]="Username";
$lng[11][3]="Email";
$lng[11][4]="Rights";
$lng[11][5]="Create new user";

//Edit users
$lng[12][1]="Edit user";
$lng[12][2]="Name";
$lng[12][3]="Username";
$lng[12][4]="Email";
$lng[12][5]="Rights";
$lng[12][6]="Update user";
$lng[12][7]="Delete user";
$lng[12][8]="Name is required!";
$lng[12][9]="Username is required!";
$lng[12][10]="Email is required!";
$lng[12][11]="Email address is not correct!";
$lng[12][12]="Are you sure? User will be deleted!";
$lng[12][13]="Assign projects";
$lng[12][14]="Save";
$lng[12][15]="All Projects:";
$lng[12][16]="Selected Projects:"; 
$lng[12][17]="Create user";
$lng[12][18]="Password is required!";
$lng[12][19]="Passwords don't match!";
$lng[12][20]="Password";
$lng[12][21]="Re-enter password";
$lng[12][22]="Reset password";
$lng[12][23]="Reset password";

//releases
$lng[13][1]="Release";
$lng[13][2]="Project";
$lng[13][3]="Projected Date";
$lng[13][4]="Released Date";
$lng[13][5]="Add new release";
$lng[13][6]="Release name"; //field Name label
$lng[13][7]="Name of the assigned project"; //field Project label
$lng[13][8]="Projected Date"; //field Projected Date label
$lng[13][9]="Released Date"; //field Released Date label
$lng[13][10]="Release cases"; //field cases label
$lng[13][11]="Cases";
$lng[13][12]="Local/global";
$lng[13][13]="Local/global"; //field Global/local label
$lng[13][14]="local";
$lng[13][15]="global";

//Edit release
$lng[14][1]="Edit release";
$lng[14][2]="Add release";
$lng[14][3]="Name";
$lng[14][4]="Project";
$lng[14][5]="Projected Date (dd.mm.yyyy)";
$lng[14][6]="Released Date (dd.mm.yyyy)";
$lng[14][7]="Update release";
$lng[14][8]="Delete release";
$lng[14][9]="Add release";
$lng[14][10]="Are you sure? Release will be deleted!";
$lng[14][11]="Name is required!";
$lng[14][12]="Projected date is required!";
$lng[14][13]="Projected date is invalid!";
$lng[14][14]="Released Date is invalid!";

//Edit requirement
$lng[15][1]="Edit requirement";
$lng[15][2]="Add new requirement";
$lng[15][3]="Project";
$lng[15][4]="Title";
$lng[15][5]="Description";
$lng[15][6]="Add requirement";
$lng[15][7]="Title is required!";
$lng[15][8]="Description is required!";
$lng[15][9]="Project is required!";
$lng[15][10]="State";
$lng[15][11]="Requirement type";
$lng[15][12]="--";
$lng[15][13]="Priority";
$lng[15][14]="URL";
$lng[15][15]="Valid";
$lng[15][16]="Author";
$lng[15][17]="Creation date";
$lng[15][18]="Last change";
$lng[15][19]="Accepted Date";
$lng[15][20]="Accepted User";
$lng[15][21]="Update requirement";
$lng[15][22]="Delete requirement";
$lng[15][23]="Are you sure? Requirement will be deleted!";
$lng[15][24]="Releases";
$lng[15][25]="*Select several releases holding pressed CTRL";
$lng[15][26]="yes";  //valid
$lng[15][27]="no";  //valid
$lng[15][28]="--select a project--";  //project dropdown
$lng[15][29]="Release date (dd.mm.yyyy)";  
$lng[15][30]="Assign to";  
$lng[15][31]="not valid/rejected";  
$lng[15][32]="valid/accepted";  
$lng[15][33]="retired";  
$lng[15][34]="Internal version";  
$lng[15][35]="Parent requirement";  
$lng[15][36]="Position in requirement tree";  
$lng[15][37]="-none-";  
$lng[15][38]="Parent";  
$lng[15][39]="Tree position";  
$lng[15][40]="Component";  
$lng[15][41]="Source";  
$lng[15][42]="Risk level";  
$lng[15][43]="Complexity";  
$lng[15][44]="Open points";  
$lng[15][45]="Req ID";
$lng[15][46]="(add 'http://' in front if external link)";  
$lng[15][51]="Project name"; //label for Project field
$lng[15][52]="Releases names"; //label for Releases field
$lng[15][53]="Requirement title"; //label for title field
$lng[15][54]="Parent requirement"; //label for Parent field
$lng[15][55]="Position in requirement tree"; //label for Position in requirement tree field
$lng[15][56]="Assign to"; //label for Assign to field
$lng[15][57]="Requirement description"; //label for Description  field
$lng[15][58]="Requirement State"; //label for State field
$lng[15][59]="Requirement type"; //label for Type field
$lng[15][60]="Requirement priority"; //label for priority field
$lng[15][61]="Requirement URL"; //label for URL field
$lng[15][62]="Requirement component"; //label for Component field
$lng[15][63]="Requirement source"; //label for Source field
$lng[15][64]="Requirement Risk level"; //label for Risk level field
$lng[15][65]="Requirement Complexity"; //label for Complexity field
$lng[15][66]="Requirement Open points"; //label for Open points field
$lng[15][67]="Req ID"; //label for Req ID field
$lng[15][68]="Requirement Author"; //label for Author  field
$lng[15][69]="Requirement Internal version"; //label for Internal version  field
$lng[15][70]="Requirement Creation date"; //label for Creation date field
$lng[15][71]="Requirement Last change"; //label for Last change  field
$lng[15][72]="Requirement Accepted Date"; //label for Accepted Date field
$lng[15][73]="Requirement Accepted User"; //label for Accepted User field
$lng[15][74]="The requirement's project is retired, requirement is not manageable!"; 
$lng[15][75]="Clone requirement"; 
$lng[15][76]="Stakeholders"; 
$lng[15][77]="Stakeholders names"; //label for Stakeholders  field
$lng[15][78]="Depends on";
$lng[15][79]="Dependencies between requirements"; //label for Depends on  field
$lng[15][80]="Conflicts";
$lng[15][81]="Conflicts between requirements"; //label for Conflicts field
$lng[15][82]="Satisfaction";
$lng[15][83]="Satisfaction"; //label for Satisfaction field
$lng[15][84]="Dissatisfaction";
$lng[15][85]="Dissatisfaction"; //label for Dissatisfaction field
$lng[15][86]="Glossary"; 
$lng[15][87]="Glossary names"; //label for Glossary  field
$lng[15][88]="Weight"; 
$lng[15][89]="Requirement weight"; //label for Weight  field
$lng[15][90]="Stub/Heading"; 
$lng[15][91]="You can create stub or heading requirements and add info in them later"; //label for Stub/Heading  field
$lng[15][92]="normal requirement"; 
$lng[15][93]="stub requirement"; 
$lng[15][94]="Add stub"; 
$lng[15][95]="Add normal"; 
$lng[15][96]="You can create stub or only heading requirements and add info in them later"; //label for Stub  button
$lng[15][97]="Subproject"; 
$lng[15][98]="Subproject"; //label for Subproject 
$lng[15][99]="Subprojects"; 
$lng[15][100]="Subprojects"; //label for Subprojects
$lng[15][101]="(lowest)"; //label for priority dropdown
$lng[15][102]="(highest)"; //label for priority dropdown
$lng[15][103]="Test cases";
$lng[15][104]="Test cases"; //label for Test cases field
$lng[15][105]="Add heading"; 
$lng[15][106]="heading requirement"; 
$lng[15][107]="Keywords";
$lng[15][108]="Keywords"; //label for Keywords field
$lng[15][109]="Please, enter a number in weight field"; 
$lng[15][110]="or add more keywords"; 
$lng[15][111]="or add more keywords"; //label for Add keywords
$lng[15][112]="(comma separated - for ex. keyword1,keyword2,keyword3, etc.)"; 
$lng[15][113]="Userfields"; 
$lng[15][114]="Comments"; 
$lng[15][115]="Components"; 
$lng[15][116]="Components names"; //label for Components  field
$lng[15][117]="This requirement has nodes and can't be deleted! Please delete or move nodes first!"; //delete error
$lng[15][118]="(Metadata needed for import)"; 

//view requirement
$lng[16][1]="View requirement";
$lng[16][2]="Edit";
$lng[16][3]="Release date";  
$lng[16][4]="Long view";  
$lng[16][5]="Short view";  
$lng[16][6]="History";  
$lng[16][7]="Comments";  
$lng[16][8]="Post comment";  
$lng[16][9]="Author";  
$lng[16][10]="Date";  
$lng[16][11]="Delete";  
$lng[16][12]="Are you sure? Comment will be deleted!";  
$lng[16][13]="hide/show Comments";  
$lng[16][14]="hide/show History";  
$lng[16][15]="PDF landscape";  
$lng[16][16]="hide/show Requirement Tree";  
$lng[16][17]="Requirement Tree";  
$lng[16][18]="Revert to this version";  
$lng[16][19]="Save";  
$lng[16][20]="There is a problem with the requirement tree - probably there are nested requirements! Please, check!";  
$lng[16][21]="PDF portrait";  
$lng[16][22]="Review comments"; 
$lng[16][23]="Post comment"; 
$lng[16][24]="Comment"; 
$lng[16][25]="Review comments"; 


//view all
$lng[17][1]="ID";
$lng[17][2]="Title";
$lng[17][3]="Author";
$lng[17][4]="Assigned to";
$lng[17][5]="Priority";
$lng[17][6]="Created date";
$lng[17][7]="Project";
$lng[17][8]="Last changed date";
$lng[17][9]="Valid";
$lng[17][10]="Waiting for Acceptance";
$lng[17][11]="Retired";
$lng[17][12]="Assigned";
$lng[17][13]="Feedback";
$lng[17][14]="Fixed";
$lng[17][15]="Implemented";
$lng[17][16]="State";
$lng[17][17]="Search";
$lng[17][18]="Text";
$lng[17][19]="Project leader";
$lng[17][20]="Date";
$lng[17][21]="Description";
$lng[17][22]="Name";
$lng[17][23]="Phase";
$lng[17][24]="Status";
$lng[17][25]="Submit";
$lng[17][26]="-don't change";
$lng[17][27]="-reset selected";
$lng[17][28]="Assign Checked Requirements:";
$lng[17][29]="--reset";
$lng[17][30]="State";  
$lng[17][31]="-don't change state";  
$lng[17][32]="valid/accepted";  
$lng[17][33]="not valid/rejected";  
$lng[17][34]="retired";  
$lng[17][35]="Project";  
$lng[17][36]="Release";  
$lng[17][37]="User";  
$lng[17][38]="-don't change project";
$lng[17][39]="Priority";  
$lng[17][40]="-don't change priority";  
$lng[17][41]="Source";  
$lng[17][42]="Component";
$lng[17][43]="There is requirement(s) assigned to retired project which is not updated!";
$lng[17][44]="Tree";
$lng[17][45]="Stub/heading";
$lng[17][46]="--show all--";
$lng[17][47]="--show only stub--";
$lng[17][48]="Open questions";
$lng[17][49]="--show all--";
$lng[17][50]="--show only open questions--";
$lng[17][51]="--show only headings--";
$lng[17][52]="Keywords";  //keywords search dropdown
$lng[17][53]="Or";  //keywords search radio button choice 1
$lng[17][54]="And";  //keywords search radio button choice 2
$lng[17][55]="Empty fields";  //empty fields search dropdown
$lng[17][56]="author";  //empty fields choice 1
$lng[17][57]="assigned to";  //empty fields choice 2
$lng[17][58]="component";  //empty fields choice 3
$lng[17][59]="release";  //empty fields choice 4
$lng[17][60]="keywords";  //empty fields choice 5
$lng[17][61]="test cases";  //empty fields choice 6
$lng[17][62]="* Drag and drop requirements to change their tree position";  //text 1
$lng[17][63]="** To change parent's positions please, click on requirement's title";  //warning text 2
$lng[17][64]="Undo";  //Undo button label
$lng[17][65]="Redo";  //Redo button label
$lng[17][66]="No undoes available!"; 
$lng[17][67]="No redoes available!"; 
$lng[17][68]="Pos"; //label at top of the tree table
$lng[17][69]="* Drag and drop requirements to change their parent position"; //text 1
$lng[17][70]="change positions"; //text 1
$lng[17][71]="Parent"; 
$lng[17][72]="Comment's author";
$lng[17][73]="Req ID";
$lng[17][74]="from";
$lng[17][75]="to";
$lng[17][76]="Pos";
$lng[17][77]="Check all";
$lng[17][78]="Uncheck all";
$lng[17][79]="Reset filter";
$lng[17][80]="Subproject";  
$lng[17][81]="-don't change subproject";
$lng[17][82]="No requirements found!";
$lng[17][83]="or";

//add comment
$lng[18][1]="Post comment";
$lng[18][2]="Submit";
$lng[18][3]="Question?";
$lng[18][4]="If you need an answer for the comment";  //Label for Question

//RSS feed
$lng[19][1]=" feed"; //anybody's feed
$lng[19][2]="Feed contains last changes in requirements of my projects";
$lng[19][3]="Requirements changes";

//XML for projects
$lng[20][1]="project";
$lng[20][2]="name";
$lng[20][3]="description";
$lng[20][4]="phase";
$lng[20][5]="status";
$lng[20][6]="leader";
$lng[20][7]="creation_date"; //no blank spaces allowed!
$lng[20][8]="release";
$lng[20][9]="name"; //release name
$lng[20][10]="assigned_users"; //no blank spaces allowed!
$lng[20][11]="name"; //assigned users name
$lng[20][12]="component";
$lng[20][13]="name"; //component name

//install/diagnostics.php
$lng[21][1]=" Testing DB connection...";
$lng[21][2]=" - DB connection can't be established! Please check for valid DB name or username or password.";
$lng[21][3]=" 1.DB connected successfully!";
$lng[21][4]=" Testing DB integrity...";
$lng[21][5]=" 2.All DB tables are present!";
$lng[21][6]=" - Table 'admin_access' is missing!";
$lng[21][7]=" - Table 'comments' is missing!";
$lng[21][8]=" - Table 'project_releases' is missing!";
$lng[21][9]=" - Table 'project_users' is missing!";
$lng[21][10]=" - Table 'projects' is missing!";
$lng[21][11]=" - Table 'releases' is missing!";
$lng[21][12]=" - Table 'requirements' is missing!";
$lng[21][13]=" - Table 'requirements_history' is missing!";
$lng[21][14]=" - Table 'users' is missing!";
$lng[21][15]=" Testing folders permissions...";
$lng[21][16]=" 3.All folders are present and with sufficient rights!";
$lng[21][17]=" - Folder 'admin' is missing or with unsufficient rights! Should be 0755.";
$lng[21][18]=" - Folder 'ini/lng' is missing or with unsufficient rights! Should be 0755.";
$lng[21][19]=" - Language file in 'ini/lng' is missing!";
$lng[21][20]=" - Folder 'admin/css' is missing or with unsufficient rights! Should be 0755.";
$lng[21][21]=" - Folder 'admin/img' is missing or with unsufficient rights! Should be 0755.";
$lng[21][22]=" - Folder 'admin/inc' is missing or with unsufficient rights! Should be 0755.";
$lng[21][23]=" - Folder 'FCKeditor' is missing or with unsufficient rights! Should be 0755.";
$lng[21][24]=" - Folder 'img' is missing or with unsufficient rights! Should be 0755.";
$lng[21][25]=" - Folder 'install' is missing or with unsufficient rights! Should be 0755.";
$lng[21][26]=" - Folder 'RSS' is missing or with unsufficient rights! Should be 0777.";
$lng[21][27]=" - Folder 'ini' is missing or with unsufficient rights! Should be 0777.";
$lng[21][28]=" - Folder 'ini/bkps' is missing or with unsufficient rights! Should be 0777.";
$lng[21][29]=" - Folder 'ini/lng' is missing or with unsufficient rights! Should be 0777.";
$lng[21][30]=" - Folder 'ini/txts' is missing or with unsufficient rights! Should be 0777.";
$lng[21][31]=" Getting project statistics...";
$lng[21][32]=" 1.Total number of projects: ";
$lng[21][33]=" - public projects : ";
$lng[21][34]=" - private projects: ";
$lng[21][35]=" - retired projects: ";
$lng[21][36]=" 2.Total number of requirements: ";
$lng[21][37]=" 3.Total number of users: ";
$lng[21][38]=" - consumer : ";
$lng[21][39]=" - user : ";
$lng[21][40]=" - supervisor user : ";
$lng[21][41]=" - supervisor IT : ";
$lng[21][42]=" - project leader : ";
$lng[21][43]=" Testing rich HTML editor availability...";
$lng[21][44]=" 4.If you can see a sample of the rich HTML editor below, the editor has been loaded successfully, otherwise please check if it is installed correctly!";
$lng[21][45]=" - Settings file - params.php in 'ini/' is missing!";
$lng[21][46]=" 5.Check if the PDF script is installed and running correctly (PHP5 only!) - ";
$lng[21][47]=" click here ";
$lng[21][48]=" - If you can view a PDF file then the script is installed, otherwise please check the installation and settings of dompdf-0.5.1";
$lng[21][49]=" - Table 'project_stakeholders' is missing!";
$lng[21][50]=" - Table 'stakeholders' is missing!";
$lng[21][51]=" - Table 'project_glossary' is missing!";
$lng[21][52]=" - Table 'glossary' is missing!";
$lng[21][53]=" 5.Check if the Excel script is installed and running correctly (PHP5 only!) - ";
$lng[21][54]=" click here ";
$lng[21][55]=" - If you can view an Excel file then the script is installed, otherwise please check the installation and settings of phpExcel";
$lng[21][56]=" - Table 'user_fields' is missing!";
$lng[21][57]=" - Table 'subprojects' is missing!";
$lng[21][58]=" - Table 'cases' is missing!";
$lng[21][59]=" - Table 'project_cases' is missing!";
$lng[21][60]=" - Table 'release_cases' is missing!";
$lng[21][61]=" - Table 'keywords' is missing!";
$lng[21][62]=" - Table 'tree history' is missing!";
$lng[21][63]=" - Table 'export_fields' is missing!";
$lng[21][64]="Your SQL version is ";
$lng[21][65]="Your PHP version is ";
$lng[21][66]=" - Table 'components' is missing!";
$lng[21][67]=" - Table 'project_components' is missing!";
$lng[21][68]=" - Table 'project_keywords' is missing!";
$lng[21][69]=" - Table 'reviews' is missing!";
$lng[21][70]=" - Table 'review_comments' is missing!";
$lng[21][71]=" - Table 'review_requirements' is missing!";
$lng[21][72]=" - Table 'review_users' is missing!";
$lng[21][73]=" - Table missing: ";

//stakeholders
$lng[22][1]="Stakeholder";
$lng[22][2]="Project";
$lng[22][3]="Function";
$lng[22][4]="Email";
$lng[22][5]="Add new stakeholder";
$lng[22][6]="Stakeholder name"; //field Name label
$lng[22][7]="Name of the assigned project"; //field Project label
$lng[22][8]="Function"; //field Function label
$lng[22][9]="Email"; //field Email label

//Edit stakeholder
$lng[23][1]="Edit stakeholder";
$lng[23][2]="Add stakeholder";
$lng[23][3]="Name";
$lng[23][4]="Project";
$lng[23][5]="Function";
$lng[23][6]="Email";
$lng[23][7]="Update stakeholder";
$lng[23][8]="Delete stakeholder";
$lng[23][9]="Add stakeholder";
$lng[23][10]="Are you sure? Stakeholder will be deleted!";
$lng[23][11]="Name is required!";
$lng[23][12]="Interests";
$lng[23][13]="Name"; //name label
$lng[23][14]="Function"; //Function label
$lng[23][15]="Email"; //Email label
$lng[23][16]="Interests"; //Interests label
$lng[23][17]="Manage stakeholders";


//glossary
$lng[24][1]="Glossary";
$lng[24][2]="Project";
$lng[24][3]="Term";
$lng[24][4]="Abbreviation";
$lng[24][5]="Add new glossary";
$lng[24][6]="Glossary ID"; //field Glossary/ID label
$lng[24][7]="Name of the assigned project"; //field Project label
$lng[24][8]="Term"; //field Term label
$lng[24][9]="Abbreviation"; //field Abbreviation label

//Edit glossary
$lng[25][1]="Edit glossary";
$lng[25][2]="Add glossary";
$lng[25][3]="ID";
$lng[25][4]="Project";
$lng[25][5]="Term";
$lng[25][6]="Abreviation";
$lng[25][7]="Update glossary";
$lng[25][8]="Delete glossary";
$lng[25][9]="Add glossary";
$lng[25][10]="Are you sure? Glossary will be deleted!";
$lng[25][11]="ID is required!";
$lng[25][12]="Description";
$lng[25][13]="ID"; //ID label
$lng[25][14]="Term"; //Term label
$lng[25][15]="Abreviation"; //Abreviation label
$lng[25][16]="Description"; //Description label
$lng[25][17]="Manage glossary";
$lng[25][18]="Abreviation is required!";

//Statistics
$lng[26][1]="Project statistics";
$lng[26][2]="Project name: ";
$lng[26][3]="Project releases: ";
$lng[26][4]="Number of requirements: ";
$lng[26][5]="Requirements assigned to: ";
$lng[26][6]="Requirements' authors: ";

//Edit subprojects
$lng[27][1]="Edit subproject";
$lng[27][2]="Add subproject";
$lng[27][3]="Subproject name";
$lng[27][4]="Description";
$lng[27][5]="Parent project";
$lng[27][6]="Update subproject";
$lng[27][7]="Delete subproject";
$lng[27][8]="A subproject name is required!";
$lng[27][9]="Are you sure? Subproject will be deleted!";
$lng[27][10]="Subproject name";  //Subproject name label
$lng[27][11]="Subproject description"; //Subproject description label
$lng[27][12]="Parent project";//Parent project label

//subprojects
$lng[28][1]="Name";
$lng[28][2]="Description";
$lng[28][3]="Parent Project";
$lng[28][4]="Create new subproject";
$lng[28][5]="Subproject name"; //field Subproject label
$lng[28][6]="Subproject description"; //field Subproject label
$lng[28][7]="Parent project"; //field Parent project label
$lng[28][8]="Subproject"; //field Parent project label

//test cases
$lng[29][1]="ID";
$lng[29][2]="Name";
$lng[29][3]="Description";
$lng[29][4]="Desired result";
$lng[29][5]="Status";
$lng[29][6]="Test case name"; //field Name label
$lng[29][7]="Description"; //field Description label
$lng[29][8]="Desired result"; //field Desired result label
$lng[29][9]="Status - active or not"; //field Status  label
$lng[29][10]="Add new test case";
$lng[29][11]="Edit"; //Edit case button
$lng[29][12]="View";  //View case button
$lng[29][13]="Short view";  //View case button
$lng[29][14]="Long view";  //View case button

//Edit cases
$lng[30][1]="Edit test case";
$lng[30][2]="Add test case";
$lng[30][3]="Name";
$lng[30][4]="Description";
$lng[30][5]="Desired result";
$lng[30][6]="Status";
$lng[30][7]="Update case";
$lng[30][8]="Delete case";
$lng[30][9]="Name is required!";
$lng[30][10]="Are you sure? Test case will be deleted!";
$lng[30][11]="Save";
$lng[30][12]="Name";  //Name label
$lng[30][13]="Description";  //Description label
$lng[30][14]="Desired result";  //Desired result label
$lng[30][15]="Status";  //Status label
$lng[30][16]="active"; //Status options
$lng[30][17]="not active";  //Status options
$lng[30][18]="Delete";
$lng[30][19]="Assign projects";
$lng[30][20]="Here you can select and assign projects to the test case"; //Assign projects
$lng[30][21]="All projects:";
$lng[30][22]="Selected projects:"; 
$lng[30][23]="Assign releases";
$lng[30][24]="Here you can select and assign releases to the test case"; //Assign releases
$lng[30][25]="All releases:";
$lng[30][26]="Selected releases:"; 

//cases
$lng[31][1]="Case";
$lng[31][2]="Name";
$lng[31][3]="Description";
$lng[31][4]="Desired result";
$lng[31][5]="Status";
$lng[31][6]="not active"; 
$lng[31][7]="active"; 
$lng[31][8]="Export in pdf";
$lng[31][9]="Name"; //field name
$lng[31][10]="Description"; //field Description
$lng[31][11]="Desired result"; //field Desired result label
$lng[31][12]="Status:\nactive, not active"; //field Status label - use \n for new line!
$lng[31][13]="Desired result"; //field Desired result
$lng[31][14]="Projects"; 
$lng[31][15]="Releases"; 
$lng[31][16]="Requirements"; 
$lng[31][17]="Case projects"; //field Case projects label
$lng[31][18]="Case releases"; //field Case releases label
$lng[31][19]="Case requirements"; //field Case requirements label
$lng[31][20]="Export into PDF"; //Export into PDF button

//manage keywords
$lng[32][1]="No";
$lng[32][2]="Keyword";
$lng[32][3]="Keyword"; //field Keyword label
$lng[32][4]="Add new keyword";

//Edit keyword
$lng[33][1]="Edit keyword";
$lng[33][2]="Add keyword";
$lng[33][3]="Name";
$lng[33][4]="Update keyword";
$lng[33][5]="Delete keyword";
$lng[33][6]="Are you sure? Keyword will be deleted!";
$lng[33][7]="Name is required!";
$lng[33][8]="Name"; //name label
$lng[33][9]="Manage keywords";

//Import
$lng[34][1]="Import CSV file";
$lng[34][2]="Please, upload a file: ";
$lng[34][3]="Upload file";
$lng[34][4]="Only CSV files accepted!";
$lng[34][5]="The file is empty or not formatted correctly as a csv!";
$lng[34][6]="Please, create a project '";  //error text 1 part 1
$lng[34][7]="' first!";  //error text 1 part 2
$lng[34][8]="There is already a requirement '";  //error text 2
$lng[34][9]="No project or wrong project name at row ";  //error text 3
$lng[34][10]="No requirement title at row ";  //error text 4
$lng[34][11]="Accepted CSV format:";
$lng[34][12]="records inserted!";
$lng[34][13]="Please, leave one row as a header on the top. The file should be in UTF-8 encoding!";
$lng[34][14]="Empty project first?";
$lng[34][15]="The file is not in UTF-8 format!";
$lng[34][16]="You can use the following CSV file as a template";
$lng[34][17]="download file";
$lng[34][18]="Import XLS file";
$lng[34][19]="How to use:";
$lng[34][20]="accepted xls files are the files generated through the export XLS function";
$lng[34][21]="the project should exists(created at first)";
$lng[34][22]="the project will be emptied before the import";
$lng[34][23]="Project;Author;Source;Date(dd.mm.yyyy);Title;Description;Keyword 1;Keyword 2;Keyword 3;Open points";
$lng[34][24]="Error: No requirements found!";
$lng[34][25]="Error: No project found!";
$lng[34][26]="Error: Not existing project - please, create it first!";

//pdf fields
$lng[35][1]="Requirement's fields to import";
$lng[35][2]="Create pdf";
$lng[35][3]="Upload file";
$lng[35][4]="Template";
$lng[35][5]="--load template--";
$lng[35][6]="Save template";
$lng[35][7]="Delete template";
$lng[35][8]="Create xls";

//components
$lng[36][1]="Component";
$lng[36][2]="Project";
$lng[36][3]="Add new component";
$lng[36][4]="Component name"; //field Name label
$lng[36][5]="Name of the assigned project"; //field Project label

//Edit component
$lng[37][1]="Edit component";
$lng[37][2]="Add component";
$lng[37][3]="Name";
$lng[37][7]="Update component";
$lng[37][8]="Delete component";
$lng[37][9]="Add component";
$lng[37][10]="Are you sure? Component will be deleted!";
$lng[37][11]="Name is required!";
$lng[37][12]="Interests";
$lng[37][13]="Name"; //name label
$lng[37][17]="Manage components";

//reviews
$lng[38][1]="Review";
$lng[38][2]="Project";
$lng[38][3]="Add new review";
$lng[38][4]="Review name"; //field Name label
$lng[38][5]="Name of the assigned project"; //field Project label
$lng[38][6]="Date";
$lng[38][7]="Date"; //field Date label
$lng[38][8]="Status";
$lng[38][9]="Status"; //field Status label
$lng[38][10]="You are not assigned to any reviews"; 
$lng[38][11]="Edit"; 
$lng[38][12]="View"; 

//Edit review
$lng[39][1]="Edit review";
$lng[39][2]="Add review";
$lng[39][3]="Update review";
$lng[39][4]="Delete review";
$lng[39][5]="Manage reviews";
$lng[39][6]="Name";
$lng[39][7]="Name"; //name label
$lng[39][8]="Name is required!";
$lng[39][9]="Are you sure? Review will be deleted!";
$lng[39][10]="Description";
$lng[39][11]="Description"; //Description label
$lng[39][12]="Status";
$lng[39][13]="Status"; //Status label
$lng[39][14]="Project";
$lng[39][15]="Project"; //Project label
$lng[39][16]="Date";
$lng[39][17]="Date"; //Date label
$lng[39][18]="Users";
$lng[39][19]="Users"; //Users label

//View review
$lng[40][1]="Requirements";
$lng[40][2]="Comments";
$lng[40][3]="comments";

//installation routine
$lng[98][1]="REQHEAP INSTALLATION";
$lng[98][2]="Database host/server name/IP";
$lng[98][3]="(incude port if necessary)";
$lng[98][4]="Database root username";
$lng[98][5]="Password";
$lng[98][6]="Preferred database name";
$lng[98][7]="Preferred database username";
$lng[98][8]="Preferred database user password";
$lng[98][9]="Install";
$lng[98][11]="Can't connect to MYSQL(with root account). Check params.";
$lng[98][12]="Successful connection to MYSQL (with root account)!";
$lng[98][13]="DB version";
$lng[98][14]="MySQL DB: New database has been created - name";
$lng[98][15]="MySQL DB user: A new database user has been created";
$lng[98][16]="Priviliges were granted to DB user";
$lng[98][17]="DB tables has been created";
$lng[98][18]="ZIP file is missing";//error msg
$lng[98][19]="File system extracted";
$lng[98][20]="DIAGNOSTICS";
$lng[98][21]="Connection file is generated";
$lng[98][22]="REQHEAP IS INSTALLED SUCCESSFULLY!";
$lng[98][23]="Continue to REQHEAP";
$lng[98][24]="Project URL";
$lng[98][25]="Project foldername";
$lng[98][26]="Admin email";
$lng[98][27]="Configuration file is generated";
$lng[98][28]="PHP version";
$lng[98][29]="In order to use the full capacity(pdf and xls exports) of ReqHeap you need PHP >= 5.0";
$lng[98][30]="Please, be sure to grant the following folder permissions recursively before proceeding:";
$lng[98][31]="/admin - 777";
$lng[98][32]="/FCKeditor - 777";
$lng[98][33]="/img - 777";
$lng[98][34]="/install - 777";
$lng[98][35]="/ini - 777";
$lng[98][36]="Not enough rights to change the permissions of the folders! Please, login as root and change to 777 the rights of the following folders:";
$lng[98][37]="Connection file can't be generated! Not enough rights - please, login as root and change to 777 the rights of the following folders:";
$lng[98][38]="Use an existing database";
$lng[98][39]="Can't connect to the DB(with secondary username/password). Check params.";
$lng[98][40]="Successful connection to DB (with secondary username/password)!";
$lng[98][41]="Database migration completed successfully!";
$lng[98][42]="Error while migrating/updating the existing database! ReqHeap may not run correctly!";
$lng[98][43]="Not existing database!";

// ADMIN / CPANEL 
$lng[99][1]="Welcome to ReqHeap Control Panel"; 
$lng[99][2]="Username:"; 
$lng[99][3]="Password:"; 
$lng[99][4]="Language:"; 
$lng[99][5]="Login"; 
$lng[99][6]="Menu"; 
$lng[99][7]="Language files"; 
$lng[99][8]="Dropdowns texts"; 
$lng[99][9]="Admin Account"; 
$lng[99][10]="Logout"; 
$lng[99][11]="Username is required!"; 
$lng[99][12]="Password is required!"; 
$lng[99][13]="ADMIN ACCOUNT"; 
$lng[99][14]="Update"; 
$lng[99][15]="DROPDOWNS TEXTS"; 
$lng[99][16]="--choose a file--"; 
$lng[99][17]="HTML is enabled here!"; 
$lng[99][18]="Save"; 
$lng[99][19]="LANGUAGE FILES"; 
$lng[99][20]="DROPDOWN TEXTS"; 
$lng[99][21]="New";
$lng[99][22]="Check for missing elements"; //lang files
$lng[99][23]="Missing whole row: ";
$lng[99][24]="Missing element: ";
$lng[99][25]="Action";
$lng[99][26]="Are you sure? The record will be deleted!";
$lng[99][27]="Load templates";
$lng[99][28]="Actions";
$lng[99][29]="Are you sure? Record will be deleted!";
$lng[99][30]="Add new";
$lng[99][31]="Back";
$lng[99][32]="Insert";
$lng[99][33]="";
$lng[99][34]="Config file";
$lng[99][35]="Checking results";
$lng[99][36]=" version";
$lng[99][37]="User defined fields";
$lng[99][38]="User defined field ";
$lng[99][39]="Name in english";
$lng[99][40]="Name in german";
$lng[99][41]="Name in french";
$lng[99][42]="Name in italian";
$lng[99][43]="Help text in english";
$lng[99][44]="Help text in german";
$lng[99][45]="Help text in french";
$lng[99][46]="Help text in italian";
$lng[99][47]="Type";
$lng[99][48]="text";
$lng[99][49]="dropdown";
$lng[99][50]="Values";
$lng[99][51]="Fill in only if you have selected a 'dropdown' type in the 'Type' field.<br>Values should be comma separated!";
$lng[99][52]="For ex. low, medium, high or 1,2,3,4,5";
$lng[99][53]="*required";
$lng[99][54]="*To remove a field simply save a blank 'Name in english'";
$lng[99][55]="Existing templates: ";  
$lng[99][56]="IT-project 1";  //name of first template
$lng[99][57]="Load template";  //Load template button
$lng[99][58]="This template has been already loaded!";  
$lng[99][59]="Template loaded successfully!";  
?>